#!/bin/sh

name=$1
path=$2
layout=$3

if [ -z "$name" ]; then
    echo "Session name required!" 2>&1
    exit 1
fi

if [ "$ZELLIJ" = "0" ]; then
    $DEV_SCRIPTS_DIR/zellij/switch "$name" "$path" "$layout"
else
    # enter directory if provided and it exists
    if [ -n "$path" ] && [ -d "$path" ]; then
        cwd=$(pwd)
        cd "$path"
    fi

    if [ -n "$layout" ]; then
        zellij --session "$name" --new-session-with-layout "$layout"
    else
        zellij --session "$name"
    fi

    # exit directory
    if [ -n "$path" ] && [ -d "$path" ]; then
        cd "$cwd"
    fi
fi
