#!/bin/sh

query=$1
shift

fzf --query="$query" \
    --info=hidden \
    --no-separator \
    --no-multi \
    --cycle \
    --height=7 \
    --layout=reverse \
    --color=fg:#c0caf5 \
    --color=fg+:#c0caf5 \
    --color=bg+:#383e5a \
    --color=prompt:#7aa2f7 \
    --color=header:#7aa2f7 \
    --color=gutter:-1 \
    --color=pointer:#7aa2f7 \
    --color=hl:#e25c74 \
    --color=hl+:#e25c74 \
    "$@"
