#!/bin/sh
source "$DEV_SCRIPTS_DIR/zellij/project"

projects_command="
    cat $ZELLIJ_PROJECT_FILE |\
    cut --delimiter ',' --fields '1'\
"

active_command="
    zellij list-sessions --no-formatting |\
    grep --invert-match 'EXITED' |\
    cut --delimiter ' ' --fields '1'\
"

dead_command="
    zellij list-sessions --no-formatting |\
    grep 'EXITED' |\
    cut --delimiter ' ' --fields '1'\
"

combined_command="{ $projects_command; $active_command; $dead_command; }"
sort_command="sort --unique"

projects_bind="ctrl-p:reload($projects_command | $sort_command)"
active_bind="ctrl-a:reload($active_command | $sort_command)"
dead_bind="ctrl-d:reload($dead_command | $sort_command)"
combined_bind="ctrl-l:reload($combined_command | $sort_command)"

selected=$(
    eval "$combined_command | $sort_command" |
    $DEV_SCRIPTS_DIR/zellij/picker "$1" \
        --header="[L] All [P] Projects [A] Active [D] Dead" \
        --bind="$projects_bind" \
        --bind="$active_bind" \
        --bind="$dead_bind" \
        --bind="$combined_bind" \
)

if [ -z "$selected" ]; then
    echo "No session selected!" 2>&1
    exit 1
fi

IFS="," read -r _ path layout < <(match_name "$selected")
open_session "$selected" "$path" "$layout"
