#!/bin/sh
name=$1
path=$2
layout=$3

if [ -z "$name" ]; then
    echo "Session name required!" 2>&1
    exit 1
fi

options="--session $name"
if [ -n "$path" ] && [ -d "$path" ]; then
    options="$options --cwd $path"
fi

if [ -n "$layout" ]; then
    options="$options --layout $layout"
fi

zellij pipe --plugin zellij-switch -- "$options"
