#!/bin/sh

ZELLIJ_PROJECT_FILE="$HOME/.zellij_projects.csv"
if ! [ -f $ZELLIJ_PROJECT_FILE ]; then
    touch $ZELLIJ_PROJECT_FILE
fi

projects_command="
    cat $ZELLIJ_PROJECT_FILE |\
    cut --delimiter ',' --fields '1'\
"

active_command="
    zellij list-sessions --no-formatting |\
    grep --invert-match 'EXITED' |\
    cut --delimiter ' ' --fields '1'\
"

dead_command="
    zellij list-sessions --no-formatting |\
    grep 'EXITED' |\
    cut --delimiter ' ' --fields '1'\
"

combined_command="{ $projects_command; $active_command; $dead_command; }"
sort_command="sort --unique"

projects_bind="ctrl-p:reload($projects_command | $sort_command)"
active_bind="ctrl-a:reload($active_command | $sort_command)"
dead_bind="ctrl-d:reload($dead_command | $sort_command)"
combined_bind="ctrl-l:reload($combined_command | $sort_command)"

selected=$(
    eval "$combined_command | $sort_command" |
    fzf --query="$1" \
        --info=hidden \
        --header="[L] All [P] Projects [A] Active [D] Dead" \
        --no-multi \
        --cycle \
        --select-1 \
        --bind="$projects_bind" \
        --bind="$active_bind" \
        --bind="$dead_bind" \
        --bind="$combined_bind" \
        --height=7 \
        --layout=reverse \
        --color=fg:#c0caf5 \
        --color=fg+:#c0caf5 \
        --color=bg+:#383e5a \
        --color=prompt:#7aa2f7 \
        --color=header:#7aa2f7 \
        --color=gutter:-1 \
        --color=pointer:#7aa2f7 \
        --color=hl:#e25c74 \
        --color=hl+:#e25c74 \
)

if [ -z "$selected" ]; then
    echo "No session selected!" 2>&1
    exit 1
fi

# Get project details if the selected session is in the projects file.
name="$selected"
path=""
layout=""
project=1
while IFS="," read -r project_name project_path project_layout; do
    if [ "$selected" = "$project_name" ]; then
        name=$project_name
        path=$project_path
        layout=$project_layout
        project=0
        break
    fi
done < $ZELLIJ_PROJECT_FILE

# Determine whether the selected session is not running ("dne"), dead (exists
# but not active), or active.
session_state="dne"
session=$(zellij list-sessions --no-formatting 2> /dev/null | grep "$name")
if echo "$session" | grep -q "EXITED"; then
    session_state="dead"
elif [ -n "$session" ]; then
    session_state="active"
fi

case $session_state in
    "dne")
        # If the selected session is not in the projects file, there is no way
        # it can appear in the list if it does not exist.
        if [ $project = 0 ]; then
            $DEV_SCRIPTS_DIR/zellij_create "$name" "$path" "$layout"
        fi
        ;;
    "dead")
        if [ $project = 0 ]; then
            # If a project session is dead, delete it and create it again. There
            # is no benefit to resurrecting a dead project session.
            zellij delete-session "$name" > /dev/null
            $DEV_SCRIPTS_DIR/zellij_create "$name" "$path" "$layout"
        else
            $DEV_SCRIPTS_DIR/zellij_attach "$name"
        fi
        ;;
    "active")
        $DEV_SCRIPTS_DIR/zellij_attach "$name"
        ;;
esac
