format = """
[](fg:#6a708e)\
$username\
$hostname\
[](fg:#6a708e bg:#6483c8)\
$directory\
[](fg:#6483c8 bg:#383e5a)\
$git_branch\
[](fg:#383e5a)\
\n\
$character
"""

[username]
disabled = false
show_always = true
format = "[$user](fg:#c0caf5 bg:#6a708e)"

[hostname]
disabled = false
ssh_only = false
format = "([@$hostname](fg:#c0caf5 bg:#6a708e))"

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
format = "[ $path](fg:#c0caf5 bg:#6483c8)"

[git_branch]
format = "([ $symbol$branch](fg:#7aa2f7 bg:#383e5a))"
